apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-kafka-consumer
  name: udaconnect-kafka-consumer
spec:
  ports:
  - name: "5000"
    port: 5000
  selector:
    service: udaconnect-kafka-consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-kafka-consumer
  name: udaconnect-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-kafka-consumer
  template:
    metadata:
      labels:
        service: udaconnect-kafka-consumer
    spec:
      containers:
      - image: rap999a/udaconnect-kafka-consumer:latest
        name: udaconnect-kafka-consumer
        imagePullPolicy: Always
      restartPolicy: Always
